=== AguilarAlexisGG/tecweb/ejemplos/XSD/Validacion_con_1_xsd/serviciovod_ns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://starfire.com/vod"
    elementFormDefault="qualified" attributeFormDefault="unqualified"
    xmlns:vod="http://starfire.com/vod">
    
    <xsd:simpleType name="region">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ARG"/>
            <xsd:enumeration value="ESP"/>
            <xsd:enumeration value="KOR"/>
            <xsd:enumeration value="MEX"/>
            <xsd:enumeration value="USA"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="tituloType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="duracion" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
    <xsd:complexType name="generoType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="titulo" type="vod:tituloType"/>
        </xsd:sequence>
        <xsd:attribute name="nombre" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="programasType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="genero" type="vod:generoType"/>
        </xsd:sequence>
        <xsd:attribute name="region" type="vod:region" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="contenidoType">
        <xsd:sequence>
            <xsd:element name="peliculas" type="vod:programasType"/>
            <xsd:element name="series" type="vod:programasType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="correoType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[^@]+@[^\.]+\..+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:attributeGroup name="perfilAttribute">
        <xsd:attribute name="usuario" use="required"/>
        <xsd:attribute name="idioma" use="required"/>
    </xsd:attributeGroup>
    
    <xsd:complexType name="perfilType">
        <xsd:attributeGroup ref="vod:perfilAttribute"/>
    </xsd:complexType>
    
    <xsd:complexType name="perfilesType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="perfil" type="vod:perfilType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="cuentaType">
        <xsd:sequence>
            <xsd:element name="perfiles" type="vod:perfilesType"/>
        </xsd:sequence>
        <xsd:attribute name="correo" type="vod:correoType" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="CatalogoVODtype">
        <xsd:sequence>
            <xsd:element name="cuenta" type="vod:cuentaType"/>
            <xsd:element name="contenido" type="vod:contenidoType"/>
        </xsd:sequence>
        <xsd:attribute name="Version" type="xsd:decimal" use="required"/>
    </xsd:complexType>
    
    <xsd:element name="CatalogoVOD" type="vod:CatalogoVODtype"/>
</xsd:schema>

=== AguilarAlexisGG/tecweb/ejemplos/XSD/Validacion_con_1_xsd/serviciovod_ns_x1.xml
<?xml version="1.0" encoding="UTF-8"?>
<vod:CatalogoVOD Version="2.0"
    xmlns:vod="http://starfire.com/vod"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://starfire.com/vod serviciovod_ns.xsd">
    <vod:cuenta correo="carlos.conderl@correo.buap.mx">
        <vod:perfiles>
            <vod:perfil usuario="NeoJC" idioma="Español"/>
            <vod:perfil usuario="Brother" idioma="Español"/>
        </vod:perfiles>
    </vod:cuenta>
    <vod:contenido>
        <vod:peliculas region="MEX">
            <vod:genero nombre="Super Héroes">
                <vod:titulo duracion="2:37">ETERNALS</vod:titulo>
                <vod:titulo duracion="2:04">CAPITAN AMÉRICA, EL 1ER VENGADOR</vod:titulo>
            </vod:genero>
            <vod:genero nombre="Animadas">
                <vod:titulo duracion="1:40">RED</vod:titulo>
                <vod:titulo duracion="1:47">RAYA</vod:titulo>
            </vod:genero>
        </vod:peliculas>
        <vod:series region="USA">
            <vod:genero nombre="Comedia">
                <vod:titulo duracion="0:30">FRIENDS</vod:titulo>
                <vod:titulo duracion="0:40">HOW I MEET YOUR MOTHER</vod:titulo>
            </vod:genero>
            <vod:genero nombre="Suspenso">
                <vod:titulo duracion="0:30">Stranger Things</vod:titulo>
                <vod:titulo duracion="0:45">Criminal Minds</vod:titulo>
            </vod:genero>
        </vod:series>
    </vod:contenido>
</vod:CatalogoVOD>
